####lyveset.sub####
####SNP phylogeny construction

#### Specify the HTCondor Universe
universe = docker
docker_image = nwflorek/lyveset:1.1.4

#### Docker will run most successfully on our new operating system, CentOS7.
requirements = (Target.HasGluster == true) && (OpSysMajorVer == 7)

#### Specify your executable.
executable = dryad/condor/lyveset.sh

#### Transfer files in
should_transfer_files = YES

#### Specify arguments
arguments = /mnt/gluster/nwflorek/lyveset reference.fasta 6 30_sal

#### Specify initaldir
initialdir = output/lyveset/

#### Specify log files
output = lyveset_$(Cluster).out
log = lyveset_$(Cluster).log
error = lyveset_$(Cluster).err

#### Resources
request_cpus = 8
request_memory = 20GB
request_disk = 1GB

#### Tell HTCondor to run 1 instances of our job:
queue 1
